### ISSUE TITLE
No IAM policies are generated

### ISSUE THREAD

**Issue by Aurrix** [iann0036/iamlive#48]
I am trying out a simple setup.
I have downloaded the latest 0.45 version executable for Windows and running
```
iamlive --set-ini
```
In another terminal, I am running
```
aws s3api list-buckets
```
Aws returns a list of buckets that I have in the account, but nothing is outputted in iamlive terminal.

I have tried this out on both Windows 10 and 11 with personal and work accounts.

**Comment by iann0036** [comment]
Hi @Aurrix,

It might be having trouble setting your AWS CLI options due to security or a number of other reasons. After starting the iamlive process, check your `.aws/config` to see if the `csm_enabled = true` option has been successfully written. You can also do this yourself if there is problems for whatever reason.

You can also invoke CSM per command line session, i.e.
```
set AWS_CSM_ENABLED=true
aws s3api list-buckets
```

or you can also attempt to use the program in [proxy mode](https://github.com/iann0036/iamlive#proxy-mode).

**Comment by Aurrix** [comment]
Yes it was set up in config file

**Comment by iann0036** [comment]
Just to test, could you confirm that if you follow the same steps for proxy mode, but _don't_ start up an iamlive window, the AWS call fails?

If not, the proxy setup may not be configured properly.

Could you also confirm you're using a standard AWS commercial region (not China / GovCloud / Osaka)?

**Comment by Aurrix** [comment]
It seems like AWS_DEFAULT_PROFILE was set in env vars, while I was using default with iamlive
